window.EDUNIZAM_STUDY_DATA={
  materials:[
    {id:"fbise-syllabus-hub",board:"FBISE Islamabad",classLevels:[9,10,11,12],subject:"All Subjects",type:"Syllabus",title:"FBISE Syllabus & Model Question Papers Hub",source:"official",url:"https://www.fbise.edu.pk/syllabus.php",note:"Official FBISE syllabus, scheme of studies and model-paper hub."},
    {id:"fbise-slo-hub",board:"FBISE Islamabad",classLevels:[9,10,11,12],subject:"All Subjects",type:"Assessment Framework",title:"FBISE SLO Assessment Frameworks & Model Papers",source:"official",url:"https://www.fbise.edu.pk/curriculum_model_paper.php",note:"Official SLO-based assessment frameworks, model papers and supporting resources."},
    {id:"fbise-scheme-2024",board:"FBISE Islamabad",classLevels:[9,10,11,12],subject:"All Subjects",type:"Scheme of Studies",title:"Inclusive Scheme of Studies 2024",source:"official",url:"https://www.fbise.edu.pk/Syllabus/Scheme-of-Studies.pdf",fileUrl:"https://www.fbise.edu.pk/Syllabus/Scheme-of-Studies.pdf",note:"Official FBISE implementation scheme for SSC/HSSC."},
    {id:"fbise-ssc1-syllabus",board:"FBISE Islamabad",classLevels:[9],subject:"All Subjects",type:"Syllabus",title:"FBISE SSC-I Syllabus & Model Papers",source:"official",url:"https://www.fbise.edu.pk/syllabusSSC-I.php",note:"Official class 9 syllabus and model-paper resources."},
    {id:"fbise-hssc1-revised",board:"FBISE Islamabad",classLevels:[11],subject:"Biology / Chemistry / Computer Science / Mathematics / Physics",type:"Model Papers",title:"FBISE Revised HSSC-I Model Papers",source:"official",url:"https://www.fbise.edu.pk/syllabusHSSC-I-revisedpaper.php",note:"Official revised model papers for HSSC-I core science subjects."},
    {id:"math-9-formula-sheet",board:"EduNizam",classLevels:[9],subject:"Mathematics",type:"Formula Sheet",title:"Class 9 Mathematics Quick Formula Sheet",source:"built-in",content:"Matrix order = rows × columns\nDeterminant of [[a,b],[c,d]] = ad − bc\nQuadratic discriminant: D = b² − 4ac\nDistance formula: d = √((x₂−x₁)²+(y₂−y₁)²)\nSlope: m=(y₂−y₁)/(x₂−x₁)"},
    {id:"math-10-formula-sheet",board:"EduNizam",classLevels:[10],subject:"Mathematics",type:"Formula Sheet",title:"Class 10 Mathematics Quick Formula Sheet",source:"built-in",content:"Quadratic formula: x=(-b±√(b²−4ac))/(2a)\nsin²θ+cos²θ=1\n1+tan²θ=sec²θ\n1+cot²θ=csc²θ\nVariation: y=kx, y=k/x"},
    {id:"physics-9-formula-sheet",board:"EduNizam",classLevels:[9],subject:"Physics",type:"Formula Sheet",title:"Class 9 Physics Quick Formula Sheet",source:"built-in",content:"Speed = distance/time\nVelocity = displacement/time\nAcceleration = Δv/Δt\nForce: F=ma\nMomentum: p=mv\nWork: W=Fd\nPower: P=W/t"},
    {id:"physics-10-formula-sheet",board:"EduNizam",classLevels:[10],subject:"Physics",type:"Formula Sheet",title:"Class 10 Physics Quick Formula Sheet",source:"built-in",content:"Wave speed: v=fλ\nOhm's law: V=IR\nElectric power: P=VI=I²R=V²/R\nCharge: Q=It\nLens formula: 1/f=1/v+1/u"},
    {id:"math-11-formula-sheet",board:"EduNizam",classLevels:[11],subject:"Mathematics",type:"Formula Sheet",title:"Class 11 Mathematics Quick Formula Sheet",source:"built-in",content:"AP nth term: aₙ=a+(n−1)d\nAP sum: Sₙ=n/2[2a+(n−1)d]\nGP nth term: aₙ=ar^(n−1)\nGP sum: Sₙ=a(1−rⁿ)/(1−r)\nPermutation: nPr=n!/(n−r)!\nCombination: nCr=n!/[r!(n−r)!]"},
    {id:"math-12-formula-sheet",board:"EduNizam",classLevels:[12],subject:"Mathematics",type:"Formula Sheet",title:"Class 12 Mathematics Quick Formula Sheet",source:"built-in",content:"d/dx(xⁿ)=nxⁿ⁻¹\nd/dx(sin x)=cos x\nd/dx(cos x)=−sin x\n∫xⁿdx=xⁿ⁺¹/(n+1)+C\n∫1/x dx=ln|x|+C\nSlope of tangent = dy/dx"}
  ]
};